#!/bin/bash

set -euo pipefail

# Get the Cloudflare IPs
curl -s https://www.cloudflare.com/ips-v4 -o /tmp/cloudflare_ips_$$
echo "" >> /tmp/cloudflare_ips_$$
curl -s https://www.cloudflare.com/ips-v6 >> /tmp/cloudflare_ips_$$

# Reset the firewall to clean stuff.
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
for ip in $(cat /tmp/cloudflare_ips_$$)
do
  ufw allow proto tcp from $ip comment 'Cloudflare'
done
# Make sure the firewall is enabled and started, as the above command
# stops it.
ufw enable
ufw reload > /dev/null
ufw status numbered
